import type { ChartAnswers } from './draft.ts';

/** Invented starting answers for a later hand check. Do not train on these. */
export const holdoutChartAnswers: readonly ChartAnswers[] = [
	{ direction: 'Finish a half marathon', timeline: 'October', situation: 'Runs twice a week', focus: 'A calm knee', constraint: 'A bad knee' },
	{ direction: 'Pass the driving test', timeline: 'Eight weeks', situation: 'Has a permit', focus: 'Parking', constraint: 'Lessons only on Saturday' },
	{ direction: 'Ship a small app', timeline: 'Twelve weeks', situation: 'Evenings free', focus: 'One screen that works', constraint: 'No weekend work' },
	{ direction: 'Read twenty books', timeline: 'This year', situation: 'Reads on the train', focus: 'Finish what I start', constraint: 'Forty minutes a day' },
	{ direction: 'Play three songs on piano', timeline: 'Six months', situation: 'Owns a keyboard', focus: 'Hands together', constraint: 'Fifteen minutes after dinner' },
	{ direction: 'Cook dinner at home', timeline: 'This month', situation: 'Orders out most nights', focus: 'Four dinners a week', constraint: 'A tiny kitchen' },
	{ direction: 'Sleep before eleven', timeline: 'Three weeks', situation: 'Scrolls in bed', focus: 'The phone leaves the room', constraint: 'Shares a room' },
	{ direction: 'Speak basic Spanish', timeline: 'Four months', situation: 'Knows a few phrases', focus: 'Ordering food', constraint: 'No classes, only an app' },
	{ direction: 'Save a month of rent', timeline: 'Six months', situation: 'Paycheck to paycheck', focus: 'One transfer on payday', constraint: 'No second job' },
	{ direction: 'Fix the back pain', timeline: 'This season', situation: 'Sits all day', focus: 'A daily walk', constraint: 'Cannot run' },
	{ direction: 'Write a short story', timeline: 'Thirty days', situation: 'Has a notebook', focus: 'Four hundred words a day', constraint: 'After the kids sleep' },
	{ direction: 'Learn to weld', timeline: 'A semester', situation: 'Shop class on Thursday', focus: 'A clean bead', constraint: 'No home shop' },
	{ direction: 'Visit my parents monthly', timeline: 'This year', situation: 'Lives two hours away', focus: 'The first Sunday', constraint: 'No overnight stays' },
	{ direction: 'Quit the afternoon soda', timeline: 'Two weeks', situation: 'Two cans a day', focus: 'Water at the desk', constraint: 'The machine is in the hall' },
	{ direction: 'Apply to three jobs', timeline: 'This month', situation: 'Unhappy at work', focus: 'A tailored letter', constraint: 'Applications after 8' },
	{ direction: 'Plant a windowsill garden', timeline: 'Spring', situation: 'One sunny window', focus: 'Herbs I will cook', constraint: 'No outdoor space' },
	{ direction: 'Hold a five-minute plank', timeline: 'Ten weeks', situation: 'Can hold thirty seconds', focus: 'Three sessions a week', constraint: 'A bad wrist' },
	{ direction: 'Learn the bus routes', timeline: 'Two weeks', situation: 'New in town', focus: 'The commute', constraint: 'No car' },
	{ direction: 'Mail the tax papers', timeline: 'Before April', situation: 'Papers in a box', focus: 'One evening to sort', constraint: 'No accountant' },
	{ direction: 'Draw every day', timeline: 'A month', situation: 'Has pencils', focus: 'Ten minutes', constraint: 'Only on the train' },
	{ direction: 'Call my sister weekly', timeline: 'This quarter', situation: 'Texts, rarely talks', focus: 'Sunday afternoon', constraint: 'She works nights' },
	{ direction: 'Rebuild the bike', timeline: 'Four weekends', situation: 'Parts are in the garage', focus: 'Brakes first', constraint: 'Borrowed tools' },
	{ direction: 'Present without notes', timeline: 'The next talk', situation: 'Reads slides', focus: 'One story', constraint: 'Ten minutes on stage' },
	{ direction: 'Eat breakfast', timeline: 'Two weeks', situation: 'Skips it', focus: 'Something before leaving', constraint: 'Out the door at 7' },
	{ direction: 'Learn SQL', timeline: 'Eight weeks', situation: 'Uses spreadsheets', focus: 'One query a day', constraint: 'Lunch break only' },
	{ direction: 'Host one dinner', timeline: 'This month', situation: 'Has not hosted', focus: 'Four people, one pot', constraint: 'A small table' },
	{ direction: 'Walk the dog daily', timeline: 'Starting Monday', situation: 'Walks are irregular', focus: 'Before work', constraint: 'Dark mornings' },
	{ direction: 'Clear the inbox', timeline: 'Five days', situation: 'Two thousand unread', focus: 'Archive, do not answer all', constraint: 'Thirty minutes a day' },
	{ direction: 'Practice guitar chords', timeline: 'Six weeks', situation: 'Knows three chords', focus: 'Clean changes', constraint: 'Apartment, so quiet hours' },
	{ direction: 'Donate unused clothes', timeline: 'This weekend', situation: 'Closet is full', focus: 'Two bags', constraint: 'No car to the shop' },
	{ direction: 'Learn to swim', timeline: 'The summer', situation: 'Avoids deep water', focus: 'Face in the water', constraint: 'Pool only on Sunday' },
	{ direction: 'Write the resume', timeline: 'This week', situation: 'Last version is old', focus: 'One page', constraint: 'Evenings' },
	{ direction: 'Stretch after sitting', timeline: 'Two weeks', situation: 'Hips are tight', focus: 'Five minutes at 3', constraint: 'An open office' },
	{ direction: 'Bake one loaf', timeline: 'Saturday', situation: 'Has never baked', focus: 'Follow the card', constraint: 'No stand mixer' },
	{ direction: 'Study for the quiz', timeline: 'Thursday', situation: 'Class is Tuesday', focus: 'Twenty minutes', constraint: 'A shared dorm' },
	{ direction: 'Set up the desk', timeline: 'Tonight', situation: 'Works from the couch', focus: 'A clear surface', constraint: 'One shelf' },
	{ direction: 'Reply to three friends', timeline: 'This week', situation: 'Left people on read', focus: 'A real sentence', constraint: 'No long calls' },
	{ direction: 'Learn the bus to the clinic', timeline: 'Before the appointment', situation: 'New clinic', focus: 'One practice ride', constraint: 'No rideshare' },
	{ direction: 'Photograph one roll', timeline: 'This month', situation: 'Camera is in a drawer', focus: 'Finish the roll', constraint: 'Weekends' },
	{ direction: 'Pay the dentist', timeline: 'Friday', situation: 'Bill is on the counter', focus: 'Call and pay', constraint: 'Office hours' },
	{ direction: 'Practice a new recipe', timeline: 'Two Sundays', situation: 'Cooks the same three meals', focus: 'One new dish', constraint: 'The shop is small' },
	{ direction: 'Journal one line', timeline: 'Thirty days', situation: 'Stops after a week', focus: 'Before bed', constraint: 'A shared bedroom' },
	{ direction: 'Organize the tools', timeline: 'One Saturday', situation: 'A messy bench', focus: 'A place for the drill', constraint: 'A small shed' },
	{ direction: 'Learn ten signs', timeline: 'Two weeks', situation: 'A deaf coworker', focus: 'Greetings', constraint: 'Practice on the commute' },
	{ direction: 'File the insurance form', timeline: 'This week', situation: 'Form is half done', focus: 'Finish and send', constraint: 'Needs a scanner' },
	{ direction: 'Run a 5k', timeline: 'Eight weeks', situation: 'Walks now', focus: 'Run one minute, walk one', constraint: 'Only flat paths' },
	{ direction: 'Teach the class once', timeline: 'Next month', situation: 'Has the outline', focus: 'A rehearsal', constraint: 'Evenings with the kids' },
	{ direction: 'Sort the photos', timeline: 'Three evenings', situation: 'Years on the phone', focus: 'One album a night', constraint: 'The phone storage is full' },
	{ direction: 'Build a bookshelf', timeline: 'A weekend', situation: 'Boards are bought', focus: 'Level shelves', constraint: 'Apartment rules on drilling' },
	{ direction: 'Ask for the raise', timeline: 'The next review', situation: 'Has the notes', focus: 'One clear ask', constraint: 'The meeting is twenty minutes' }
];
